# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:39:31+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ExternalAccountKey(BaseModel):
    b64MacKey: Optional[str] = Field(
        None,
        description='Output only. Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created',
    )
    keyId: Optional[str] = Field(
        None,
        description='Output only. Key ID. It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Resource name. projects/{project}/locations/{location}/externalAccountKeys/{key_id}',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
